# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.cache/wt} [current_project]
set_property parent.project_path {C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.srcs/sources_1/new/EightXEight.sv}
  {C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.srcs/sources_1/new/sevSeg4digit.sv}
  {C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.srcs/sources_1/new/GameClass.sv}
}
read_xdc {{C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.srcs/constrs_1/new/const.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/MONSTER/Desktop/LECTURES/CS 223/ledTest/ledTest.srcs/constrs_1/new/const.xdc}}]

synth_design -top GameClass -part xc7a35ticpg236-1L
write_checkpoint -noxdef GameClass.dcp
catch { report_utilization -file GameClass_utilization_synth.rpt -pb GameClass_utilization_synth.pb }
